workflows:
  ios-release:
    name: iOS Release (TestFlight)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.marakiib"
        APP_STORE_APP_ID: 6473254943
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: 3.29.2
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
      cancel_previous_builds: true

    scripts:
      - name: Validate App Store Connect API Key
        script: |
          echo "🔑 PRIVATE KEY LENGTH: ${#APP_STORE_CONNECT_PRIVATE_KEY}"
          echo "🔑 KEY ID: $APP_STORE_CONNECT_KEY_IDENTIFIER"
          echo "🔑 ISSUER ID: $APP_STORE_CONNECT_ISSUER_ID"

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Generate localization files
        script: |
          flutter gen-l10n || true

      - name: Install CocoaPods
        script: |
          find ios -name "Podfile" -execdir pod install \;

      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-infos || true

      - name: Build IPA
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
          echo "📦 Build number: $BUILD_NUMBER"

          flutter build ipa --release \
            --export-method app-store \
            --build-name=11.0.4 \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
        submit_to_app_store: false

      email:
        recipients:
          - sm4679313@gmail.com
        notify:
          success: true
          failure: true
