default_platform(:ios)

platform :ios do
  desc "Build and upload to App Store"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key: File.read(ENV['AUTHKEY_PATH'])
    )

    increment_build_number

    build_app(
      scheme: ENV['SCHEME'] || "Runner",
      export_method: ENV['EXPORT_METHOD'] || "app-store",
      clean: true,
      output_directory: "./fastlane/output"
    )

    upload_to_app_store(api_key: api_key)
  end
end
